### ISSUE TITLE
How about multi-Language support

### ISSUE THREAD

**Issue by MiuKaShi** [james1236/backseat.nvim#13]
It is a very interesting GPT nvim plugin, I think it might be better to add multi-language support for feedback, like
```
require("backseat").setup({
            ---
            languages = 'english', --language (it can be english, japanese, chinese or more)

            ---
        })
```

**Comment by james1236** [comment]
Setting ` additional_instruction = "Respond in chinese, but keep the text 'line=' the same",` seems to work

**Comment by MiuKaShi** [comment]
> Setting ` additional_instruction = "Respond in chinese, but keep the text 'line=' the same",` seems to work

Thanks for the reply, but unfortunately in the GPT3 model, this setting doesn't work

**Comment by MiuKaShi** [comment]
I have try to add this function and send a pull requests. If you think it's worth, you can check it

**Comment by james1236** [comment]
Thank you!
