### ISSUE TITLE
Entries are always truncated if custom section includes whitespace separator (%=)

### ISSUE THREAD

**Issue by williamboman** [james1236/backseat.nvim#16]
Hello! Since 59f96560c659a79dba941efac25ed6e20c369375, barbecue entries are always truncated because
I've configured `custom_section` to be prefixed with `%=` so that it is right-aligned. This results
in `custom_section_length` to be very large because it includes a bunch of leading spaces (the
padding necessary to right-align it), effectively triggering truncation every time.

Not sure what the best way to work around this would be. After looking into the code my first idea
was that it might be best to construct the complete winbar and `nvim_eval_statusline()` it to see if
truncation needs to be applied. The winbar already rearranges items in case it overflows, so another
option would be to simply not do any custom truncation at all and delegate that to Neovim.

Thanks!

**Comment by williamboman** [comment]
Sorry, wrong repo (I blame the `gh` CLI) 🙈, feel free to delete the issue entirely

**Comment by james1236** [comment]
No problem haha, although now I have know what a barbecue entry is!
