### ISSUE TITLE
[Help] Backseat > OpenAI Error: The model: `gpt-4` does not exist

### ISSUE THREAD

**Issue by dinhmai74** [james1236/backseat.nvim#4]
I got this error when using it as a gpt-4 model.

The config 

``` require("backseat").setup({
    openai_api_key = '',         -- Get yours from platform.openai.com/account/api-keys
    openai_model_id= "gpt-4",
    -- split_threshold = 100,
    additional_instruction = "Respond snarkily", -- (GPT-3 will probably deny this request, but GPT-4 complies)
    highlight = {
        icon = '🛰️', -- ''
        group = 'Comment',
    }
  })
```

<img width="915" alt="image" src="https://user-images.githubusercontent.com/40544043/229684371-45cbe071-1034-4f6a-86eb-3e6ecd9712e2.png">

**Comment by dinhmai74** [comment]
it works fine when remove openai_model_id

**Comment by james1236** [comment]
Hi, do you have access to the chat gpt-4 model at [this link](https://platform.openai.com/playground?mode=chat&model=gpt-4)? I think it's only available at the moment if you apply for the waiting list using your account's organization id (I don't have an organization but I applied anyway and got accepted)

**Comment by EpsilonKu** [comment]
I guess u need add warning to readme

**Comment by james1236** [comment]
> I guess u need add warning to readme

Done, thanks
