### ISSUE TITLE
feature: windows support

### ISSUE THREAD

**Issue by luiz00martins** [james1236/backseat.nvim#7]
Hi, first and foremost, great plugin!

I've tested it on both Pop_OS, and Windows 10. It works fine on Pop_OS. On windows however, it fails with `Backseat > Bad or no response:`. I assume it's because the plugin uses some linux-specific constructs.

It would be nice to have it operational on windows.

**Comment by yngwi** [comment]
I also get the "Bad or no response" error on Windows. I am using the environment variable config option, another nvim plugin, [ChatGPT](https://github.com/jackMort/ChatGPT.nvim), uses the same way to get the API key and here everything works.

**Comment by james1236** [comment]
Attempted to fix this in commit 22f49f29421e6d132f501e2e214d4d377c0e0de9, please update and tell me if it works!

**Comment by james1236** [comment]
Actually, I've just realised that xxd works in windows for me because of WSL integration. I'll see if I can find another fix

**Comment by james1236** [comment]
Ok, a better fix now in commit e2153cfbea571bf1dcefaf8384b6c51aab20a842, see if that works

**Comment by luiz00martins** [comment]
Just tried. Same response:
```
2023-04-05T17:45:51 Messages   INFO Backseat > Sending init.vim (split into 3 requests) and waiting for response...
2023-04-05T17:45:51 Messages   INFO Backseat > Bad or no response:
```

**Comment by james1236** [comment]
> 

I wasn't writing the temp file correctly, how about now with commit aa3926465ca000549ab2e0d54f7ae5a07cbd4756?

**Comment by luiz00martins** [comment]
It does!! :D

Thanks a lot for the fix!

**Comment by james1236** [comment]
Great! Thank you for being my command line for a bit!
